name: WILDERNESS STUDIO
favicon: null
layout_spectrum: 0.15163
typography_spectrum: 0.55342
title: WILDERNESS STUDIO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e3de'
    - '#908373'
    - '#190f02'
    - '#423e35'
    - '#5f5c55'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
