name: WILDERNESS STUDIO
favicon: null
layout_spectrum: 0.15163
typography_spectrum: 0.55342
title: WILDERNESS STUDIO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9730583960190415
  lightness: 0.24701829487457871
  saturation: 0.844984091585502
  rhythmicContrast: 0.8897384735755622
purpose: []
